# Generated by Django 4.2.23 on 2025-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True)),
                ('platforms', models.CharField(choices=[('YT', 'Youtube'), ('VM', 'Vimeo'), ('DM', 'Dailymotion')], default='YT', max_length=2)),
                ('upload_status', models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Failed')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
