# Generated by Django 5.2.5 on 2025-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='dailymotion_upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='videopost',
            name='dailymotion_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videopost',
            name='vimeo_upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='videopost',
            name='vimeo_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videopost',
            name='youtube_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='videopost',
            name='youtube_upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='videopost',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='platforms',
            field=models.JSONField(default=list),
        ),
    ]
