# Generated by Django 5.2.5 on 2025-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_videopost_dailymotion_upload_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='dailymotion_upload_status',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='vimeo_upload_status',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='youtube_upload_status',
        ),
        migrations.AddField(
            model_name='videopost',
            name='dailymotion_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='videopost',
            name='vimeo_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='upload_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
