# Generated by Django 5.2.5 on 2025-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_remove_videopost_dailymotion_upload_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='upload_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
